# Generated by Django 5.2.4 on 2025-08-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_is_seller_back_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
    ]
