# Generated by Django 5.2.5 on 2025-08-15 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_message_options_message_conversation_starter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation_starter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages_set', to='core.message'),
        ),
    ]
