# Generated by Django 5.2.5 on 2025-08-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_message_conversation_starter'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
