# Generated by Django 5.2.5 on 2025-08-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_is_public_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
